url: https://flaviacercalavoro.github.io
baseurl: 

# Site settings
title: Il curriculum di Flavia
email: flaviacercalavoro@gmail.com
description: "Datemi un colloquio di lavoro e un'opportunità e solleverò il mondo."


# Team names, titles and social links
people:
- name: Flavia
  pic: 1
  position: Ricercatrice di lavoro
  social:
    - title: monster
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: monster
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Roma
  - line: Italia

# Build settings
markdown: kramdown
permalink: pretty
